### ISSUE TITLE
There is a reference problem... 

### ISSUE THREAD

**Issue by hanglei** [johntrimble/foil-python#2]
When I tried to run the program cmd terminal I met with this error meg as follow File "FamilyTreeTestCase.py", line 3, in <module>
 from trimlogic.test.helper import FoilTestCase ImportError: 
No module named trimlogic.test.helper

**Comment by flaviasalisboa** [comment]
I´m experiencing the same problem, is there anything we need to set previously?

/src# python trimlogic/test/FamilyTreeTestCase.py
Traceback (most recent call last):
  File "trimlogic/test/FamilyTreeTestCase.py", line 3, in <module>
    from trimlogic.test.helper import FoilTestCase
ImportError: No module named trimlogic.test.helper

Thanks.

**Comment by annapaux** [comment]
Adding these two lines on top of the `FamilyTreeTestCase.py` file should do it:
```
import sys, os
sys.path.append(os.path.join(os.path.dirname(__file__), '..', '..'))
```
Source: https://stackoverflow.com/questions/7505988/importing-from-a-relative-path-in-python
